### ISSUE TITLE
Uknown Type 11

### ISSUE THREAD

**Issue by striderxfossility** [maximegmd/CyberEngineTweaks#631]
```
    local root = Game.GetPlayer():FindComponentByName('root')
    local animRig = root.rig

    print(Dump(animRig, false))
```

![image](https://user-images.githubusercontent.com/17473356/143781934-6175d19d-49dd-425b-94b9-8c13f014dc1f.png)

![image](https://user-images.githubusercontent.com/17473356/143781918-7e2b4d64-f9a8-4f8f-a1de-3dda6de364ec.png)

**Comment by WSSDude** [comment]
This is quite old at this point, if it is still an issue, feel free to reopen.
