### ISSUE TITLE
Not returning errors for invalid commands

### ISSUE THREAD

**Issue by anon56003269** [maximegmd/CyberEngineTweaks#698]
Try the following command in the CET console:
`Game.AddToInventory("Items.SQ031_SamuraiJacket",1)`
As of the latest CET version for game version 1.6, it results in a no-op, but nothing is output. I would expect an error, such as "Error: Missing item code"

The actual command that would result in an op due to a valid item id code would be
`Game.AddToInventory("Items.SQ031_Samurai_Jacket", 1)`

https://wiki.redmodding.org/wolvenkit/getting-started/creating-a-mod actually has the wrong item code, and troubleshooting this was difficult without an error

**Comment by dragonzkiller** [comment]
Super old "issue" right now, but this isn't a bug with CET. The `AddToInventory` function doesn't print anything no matter the status and there's no way for CET to know otherwise.

I actually wrote a custom `AddToInventory` function for my personal to handle this exact "issue"
