### ISSUE TITLE
CET doesn't display correctly when using HDR10 scRGB.

### ISSUE THREAD

**Issue by Daniel-USA** [maximegmd/CyberEngineTweaks#777]
[https://i.imgur.com/TYXZXNy.png](url)

[https://i.imgur.com/vtxJoms.png](url)

![cet visible](https://user-images.githubusercontent.com/11565004/209930701-2c095b4d-d648-46f8-be9d-79976199d70b.png)

![cet translucent](https://user-images.githubusercontent.com/11565004/209930716-d787cbac-1f62-488a-9226-bb18bd893ec3.png)

**Comment by WSSDude** [comment]
Marking as wont fix, issue of ImGui backends.
