### ISSUE TITLE
The game freezes in the tunnel near Afterlife with "disable boundary teleport" option enabled

### ISSUE THREAD

**Issue by shmerl** [maximegmd/CyberEngineTweaks#799]
I hit a peculiar bug (happens both with 1.23 and 1.22).

When in the walking tunnel near Afterlife, the image of the game freezes, though the sound keeps playing. When the boundary teleport option is off, it all works fine.

See attached save where this can be reproduced: [cp2077_save.zip](https://github.com/yamashi/CyberEngineTweaks/files/10902344/cp2077_save.zip)

My current version of the game is latest 1.61 + DLSS from GOG. I'm running it in Wine 8.3 + vkd3d-proton so not sure if this happens on Windows too or not.

**Comment by 13k** [comment]
See #653. Try disabling the option "Disable Boundary Teleport" in settings.

**Comment by shmerl** [comment]
Yeah, I know, I literally mention it in the bug report :)

Is there some way to fix it in CET though?

**Comment by WSSDude** [comment]
If this can be reproduced on latest CET version, feel free to reopen.
