### ISSUE TITLE
ImGui: Lua access to WindowMenuButtonPosition

### ISSUE THREAD

**Issue by rp-freakaz** [maximegmd/CyberEngineTweaks#811]
A small request, but it would make ImGui styling more flexible.

ImGuiStyle.WindowMenuButtonPosition is accessible via the Style Editor, but has no Enum in the Lua accessible area (ImGuiStyleVar.WindowMenuButtonPosition). So its not possible to hide or move the window title arrow, as the primary color is shared with the Window Title. Atleast not without sacrificing the entire Window Title.

The needed ImGuiDir is already accessible.

**Comment by Nats-ji** [comment]
try this
`ImGui.GetStyle().WindowMenuButtonPosition = ImGuiDir.Right`

**Comment by rp-freakaz** [comment]
works like a charm, thank you!
