### ISSUE TITLE
Amending Video options crashes the game (CP2077 v 1.62)

### ISSUE THREAD

**Issue by Sushi-Zero** [maximegmd/CyberEngineTweaks#814]
Since installing CP2077 v 1.62, installing CET 1.24 or below cause the game to crash if I change any options in CP2077 video options. The game freezes and a few moments later then close the game. The option changes appear to have taken place when logging back in. CET is not the only mod affected. This was determined by removing all my mods then enabling them one at a time. If using a clean install of CP2077 with no mods the game works fine. There are some mods with no dependencies which I have install since and they all work fine.

**Comment by WSSDude** [comment]
Latest build 1.25.2 should be a bit more stable. If you use fullscreen, switch to borderless windowed mode as alt+tab and resolution changes may cause a crash still.

This is same as #800 I believe, closing this for now.
