### ISSUE TITLE
Only worked the first day

### ISSUE THREAD

**Issue by Guarmanda** [maximegmd/CyberEngineTweaks#815]
I installed it two days ago, and today I started the game, and the tweaks did'nt start with it. I tryed overwriting the files, no change. But the tweaks did worked the first day so... I don't know what to do to reproduce/fix this

**Comment by ScomComputers** [comment]
@Guarmanda
There was a game update today, that's why it doesn't work, be patient and they will update it !

**Comment by Guarmanda** [comment]
> @Guarmanda
> There was a game update today, that's why it doesn't work, be patient and they will update it ! 

Oh sorry, didn't realise it, I will be^^

**Comment by Ijustwanttheupdate11** [comment]
Hey, is there an update? like working on it, or is it one of those, work around not have CET?

**Comment by gir489returns** [comment]
> I recommned adding a code to automate the target address finding in namespace CyberEngineTweaks::Addresses, since you already know the code pattern to search for, just ignore the RVA's in the search.

The way it's coded as a header, he can't.

**Comment by tbruckschlegel** [comment]
> > I recommned adding a code to automate the target address finding in namespace CyberEngineTweaks::Addresses, since you already know the code pattern to search for, just ignore the RVA's in the search.
> 
> The way it's coded as a header, he can't.

I assume from his knowledge moving it out of a header wouldn’t be a problem or generate a complete header file …

**Comment by maximegmd** [comment]
We don't use patterns at runtime because that's not the only thing that changes. Offsets of structures can change and we don't want a swarm of "it crashes the game" on every patch.

**Comment by tbruckschlegel** [comment]
You got me wrong, I did not mean at runtime, at as tooling to reduce manual work.

**Comment by maximegmd** [comment]
We do have automatic tooling, we just run the script from IDA and it updates things for us.

**Comment by tbruckschlegel** [comment]
Great and thanks for all the hard work!!!
