### ISSUE TITLE
[crash]

### ISSUE THREAD

**Issue by SerdarSrl** [maximegmd/CyberEngineTweaks#819]
Trying to get to the new player apartmant but noı luck when i trying near them allways getting crush, 

[Cyberpunk2077.zip](https://github.com/maximegmd/CyberEngineTweaks/files/11414762/Cyberpunk2077.zip)
![screenshot](https://user-images.githubusercontent.com/87722015/236672164-43fb0971-5c07-4cff-a57a-2fbd2567c7d9.png)

the screenshot is near the japantown apartment...

**Comment by WSSDude** [comment]
This is too old at this point I'd say due to new patches and changes... If you can reproduce it in new game patch with clean CET, no other mods (including all non-CET mods) then feel feee to reopen.
