### ISSUE TITLE
CET producing GPU hang and Windows reboot when alt tabbing or changing video options

### ISSUE THREAD

**Issue by reyrarnfredur** [maximegmd/CyberEngineTweaks#820]
The game crashes when alt tabbing or changing video options, right after a brief GPU hang. Afterwards, if I try to open the game again, it reboots my computer. 

Game version:  steam 1.62.02
CET version: 1.24.1

Stack trace:
Error reason: Assert
Expression: <Unknown>
Message: Gpu Crash for unknown reasons! Callstack here is probably irrelevant. Check if Breadcrumbs or Aftermath logged anything useful.
File: E:\R6.Release\dev\src\common\gpuApi\src\dx12\gpuApiDX12Error.cpp(42)

System information:
      Time of this report: 5/11/2023, 04:07:26
             Machine name: DESKTOP-EUR5EIT
               Machine Id: {4E6039E4-206B-4446-BCD2-4EF6DDFB2559}
         Operating System: Windows 10 Home 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
                 Language: Spanish (Regional Setting: Spanish)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: B550 AORUS ELITE V2
                     BIOS: FB (type: UEFI)
                Processor: AMD Ryzen 5 5600X 6-Core Processor              (12 CPUs), ~3.7GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16308MB RAM
                Page File: 8050MB used, 41024MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.0.8
           DxDiag Version: 10.00.19041.2075 64bit Unicode

**Comment by Code-Xer0** [comment]
I'm having the exact same issue. 5800x3D 6900XT

**Comment by maximegmd** [comment]
Another good reason to not buy AMD GPUs I guess, sorry but I can't fix their drivers...

**Comment by Code-Xer0** [comment]
I actually figured it out. Turns out I had some weird driver stuff
happening I ran a ddu and now it doesn't break anymore hah
