### ISSUE TITLE
A command that used to work no longer does.

### ISSUE THREAD

**Issue by MonsieurLedoux** [maximegmd/CyberEngineTweaks#824]
Hi everybody !

To modulate my progress in the game I used to use to freeze/unfreeze the in-game clock with :

> - Game.GetTimeSystem():SetPausedState(true, CName.new())
> - Game.GetTimeSystem():SetPausedState(false, CName.new())

Until now I was alternating without any problem. But recently, and without any other mod added in the meantime, I get an error message when I try to "unfreeze" the clock :

> > Game.GetTimeSystem():SetPausedState(false, CName.new())
> sol: runtime error: [string "Game.GetTimeSystem():SetPausedState(false, CN..."]:1: Function 'SetPausedState' requires 0 parameter(s).
> stack traceback:
> 	[C]: in function 'SetPausedState'
> 	[string "Game.GetTimeSystem():SetPausedState(false, CN..."]:1: in main chunk
> Command failed to execute!

The problem occurs no matter what savefile I load.
I did a clean re-install of the game and didn't add any mod other than the latest version CET. Doesn't work. 
I tried to edit the save with _Save Editor (Project CyberCAT-SimpleGUI)_ but I found nothing related to the in-game clock...

I don't understand command lines at all, I don't know what to do and I can't progress in the game because of this.

If anyone has a solution or even just some advice, I'm interested !

![command_failed_to_execute](https://github.com/maximegmd/CyberEngineTweaks/assets/134166938/e0f754fa-4d2e-45bd-aa3f-3ab58ac8929b)

**Comment by WSSDude** [comment]
SetPausedState waa apparently updated, it has 0 arguments so what you had put there in () is the issue.
