### ISSUE TITLE
Crashes When loading a Save from pre-installation

### ISSUE THREAD

**Issue by Call-Me-Zephyr** [maximegmd/CyberEngineTweaks#828]
Dunno if this is something I just somehow missed in the wiki, but i scoured it and didn't see anything about it. Went through a whole lotta trouble shooting processes to find out why it was crashing when i tried to load my most recent save, I'd get through part of the loading process (ex. when the newscaster is speaking on the tv,) but after a few moments the game would crash. But on starting an entirely new game, it worked fine. 

Note: It seems like its only some of the saves, as one of the other older playthroughs i have going also works, but its inconsistent and i can't find out a pattern on why.

**Comment by WSSDude** [comment]
Mods may save things into persistent storage in save. My guess is that some mod saved something there at some point and now you miss it, making the save corrupt.

CET by itself does not do this, but its moda may save things. Same may happen with any redscript mod, RED4ext mod, redmod,... Anything that can access relevant script functions.
