### ISSUE TITLE
Console not launching OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by Hearthing** [maximegmd/CyberEngineTweaks#829]
I followed the instructions on the Wiki to install CET. I'm running game version 1.62 on Steam and the CET hotfix for 1.62. I have the files installed in my /bin folder, I ran protontricks and setup winecfg while following the instructions, I have REDmod installed as well and enabled in the CP77 launcher. When I run the game, I am not prompted to set a keybind for CET. I also do not get a .log file in my cyber_engine_tweaks folder after running and exiting the game. All overlays are turned off, I'm running the game in Windowed mode. This is a fresh install of CP77. I also do not have a .config file anywhere.
![Screenshot_20230617_115459-1](https://github.com/maximegmd/CyberEngineTweaks/assets/7231850/a79c2019-abfa-47cf-9836-44c5a6aa0645)

**Comment by teleprint-me** [comment]
I encountered the same issue, and after a bit of troubleshooting, I was able to get it working. Here's how I did it:

1. I started by following the [installation instructions](https://wiki.redmodding.org/cyber-engine-tweaks/getting-started/installing) on the official wiki.

2. The mod didn't load as expected and no logs or files were generated to help diagnose the issue.

3. To address this, I ran the following command in the terminal to install some required components with Protontricks: `protontricks 1091500 --gui`. This opened the Protontricks GUI for Cyberpunk 2077.

4. In Protontricks, I selected "Select the default wineprefix", then "Run winecfg". In the window that opened, I selected the 'Libraries' tab. I added overrides for "version", "d3dcompiler_47", and "vcrun2019", clicked "Add", then "Apply" and "Ok".

5. I re-opened Protontricks and selected "Select the default wineprefix", then "Install a Windows DLL or component". I ticked "vcrun2019" and "d3dcompiler_47", and followed the steps to install those runtimes.

6. After setting up the necessary components, I launched the game through Steam. The Cyber Engine Tweaks mod loaded as expected, and I was prompted by the mod for the first time.

Please note, I made sure there were no other mods installed that could potentially interfere with the setup.

Remember, if you have vcrun2019 installed and it breaks your game, it has been reported that you can fix it without reinstalling by deleting the contents of `/steamapps/compatdata/1091500`.

This worked for me, and I hope it helps you and others facing the same issue. It would be great if the devs could add these steps to the wiki to help out Linux users!

**Comment by overcatbe** [comment]
Hi, also playing on steam - linux slackware. 
Starting the game with this launcher option:
WINEDLLOVERRIDES="winmm,version=n,b" %command% --launcher-skip

The console is not coming up. Would be nice if some default shortcut key/combination could be assigned.

**Comment by teleprint-me** [comment]
Make sure you have the following dependencies installed on your distribution: `vulkan`, `wine`, `winetricks`, and `protontricks`. Run `protontricks` and follow the instructions provided.

While environment variables shouldn't generally interfere with the process, it's recommended to exclude them unless necessary, particularly during the initial setup of the mod. 

Keep in mind that certain games may require specific flags to launch in certain environments, and those flags should be retained in such cases.

**Comment by WSSDude** [comment]
I dont know why everyone nonstol writes about the VC++ 2019 runtime in regards to Linux, even in readme, it is mentioned CET requires VC++ 2022 redistributable.

It may look like it is doing something but it causes crashes for most, not much else... Right runtime is half the thing...

And tbh, I actually didnt even had to install it personally, nor did I had to use protontricks last time I tried to make CET run under linux. All I did was to rename version.dll to bink2w64.dll and former bink2w64.dll to bink2w64Hooked.dll (note the case of the filenames).

**Comment by WSSDude** [comment]
Just noticed it is not in readme, just in troubleshooting guide... So ok, I guess this is partially on us... Will add it to readme also.

**Comment by WSSDude** [comment]
I'd like to keep this in one place ideally, could be categorised as issue with proton... Closing this in favor of #821 .

**Comment by jjzazuet** [comment]
@WSSDude confirmed that DLL renaming works like a charm :+1: (Debian 12, CP2077 v1.63). Cheers!
