### ISSUE TITLE
CET locks display to 1920x1080

### ISSUE THREAD

**Issue by Hippyspacewitch** [maximegmd/CyberEngineTweaks#842]
Launching from cyberpunk.exe and use Steam

when CET is active, setting default to 1920x1080 and upon resetting and applying them in the menu to 3840x2160 they default and shrink the window back to 1920x1080.

I have tried everything and the only way O can get the setting to change is to edit usersettings.json and continue on launch, but the game resets to 1920x1080 upon entering a menu in game (inventory or settings).  This is related to the new version of CET - this was not an issue with the pre June 28th updated mod

please help

**Comment by Nats-ji** [comment]
does this happen when you only have CET installed (no other mods besides CET)? 
It would be helpful if you can provide a screen recording, so we can better understand how to reproduce this issue.

**Comment by WSSDude** [comment]
If you use AMD gpu, think there is your culprit... Their drivers are not thar robust...
It may have been related to fonts PR also I guess, if you can repro this with new game version and CET, and are not using AMD gpu, feel free to reopen.
