### ISSUE TITLE
game is 1.6.3

### ISSUE THREAD

**Issue by punxer** [maximegmd/CyberEngineTweaks#846]
Unsupported game version! Only 1.6301 is supported. what is 1.6301

**Comment by zhjckfd135** [comment]
I downloaded version 1.25.0, everything worked for me. I'm playing on a pirated version of 1.63, maybe a hotfix has already been released.

**Comment by Smokemic** [comment]
> Unsupported game version! Only 1.6301 is supported. what is 1.6301

same here
