### ISSUE TITLE
i f*** up i need help

### ISSUE THREAD

**Issue by idan2047** [maximegmd/CyberEngineTweaks#847]
ok so i couldn't start the tapeworm job and i didnt know that they changed it to start with honaka so i played with the console code and added the debugs and now when i finish the main missions ecsept takemora she did not call me for the first time ( first call with her) like she did before in thelast save before the debug codes
because i started the save befor her call to see if the tapeworm will start like in 2020
when you puke but they changed it and now hanako wont call me

**Comment by maximegmd** [comment]
For end use support please ask on discord.
