### ISSUE TITLE
There is no commands like Game.RemoveEffectPlayer, etc

### ISSUE THREAD

**Issue by f1den** [maximegmd/CyberEngineTweaks#857]
Is there some list of functions?
with info about them if its possible NOW

**Comment by js-ware** [comment]
Functions I've confirmed do not work with the 2.0 Alpha version of CET:

"GiveDevPoints", "SetAtt", "ApplyEffectOnPlayer", & "ModStatPlayer"

Functions that I've confirmed still work with the 2.0 Alpha version of CET:

"SetLevel", AddToInventory"

Some syntax changes also, like for adding a vehicle, replace single quotes with double quotes:

Game.GetVehicleSystem():EnablePlayerVehicle('Vehicle.v_standard2_villefort_cortes_player', true, false)

becomes:

Game.GetVehicleSystem():EnablePlayerVehicle("Vehicle.v_standard2_villefort_cortes_player", true, false)

**Comment by RDP8** [comment]
Had some trouble with setlevel, I tried it and it didn't throw me an error but didn't actually give/set my level.

**Comment by bloodaxis** [comment]
Can you set debug facts currently, Game.SetDebugFact("fact", 1) doesn't seem to work.

**Comment by js-ware** [comment]
> GiveDevPoints

OLD: Game.SetLevel("StreetCred", 5)
NEW: Game.SetLevel("StreetCred", 5, 1)

Where "5" is the level you want.

**Comment by RDP8** [comment]
> > GiveDevPoints
> 
> OLD: Game.SetLevel("StreetCred", 5) NEW: Game.SetLevel("StreetCred", 5, 1)
> 
> Where "5" is the level you want.

Thanks ill give this a try.

**Comment by js-ware** [comment]
> Can you set debug facts currently, Game.SetDebugFact("fact", 1) doesn't seem to work.

_sol: runtime error: [string "Game.SetDebugFact("fact", 1)"]:1: Function SetDebugFact is not a GameInstance member and is not a global._

So the function SetDebugFact also has changed.

**Comment by dragonzkiller** [comment]
These missing commands are NOT a CET issue. If they have been removed from the game, CET will not find them

**Comment by maximegmd** [comment]
Should be fixed, additional missing functions were removed from the game.

**Comment by jhirn** [comment]
I'm certain you guys are up to your neck fixing things post patch. Is SetDebugFact (or another method) something that can be revived or is it no longer possible to update such things via console? I'm dumb and need to update where I sent Jackie. 

Is this a value that can be found/set directly in a TweakDB Editor Record? New to CET so not sure how to navigate it. 

`Game.SetDebugFact("q005_jackie_to_mama", 1)`
