### ISSUE TITLE
Gameplay stutters with CET 2.0

### ISSUE THREAD

**Issue by r0gler** [maximegmd/CyberEngineTweaks#860]
As shown in the video, after installing CET, my game freezes for a brief amount of time every second or so. The other mods I am using are:

- Appearance Mod Menu
- Simple Menu
- Better Vehicle First Person

*Edit: seems that Simple Menu is causing this bug.

https://github.com/maximegmd/CyberEngineTweaks/assets/107191786/5368c0b2-1168-4ae9-a459-32dd723c848b

**Comment by maximegmd** [comment]
Report the issue to Simple Menu, it seems to be the only offender, likely an API change causing it to spew a lot of logs.
