### ISSUE TITLE
Function LevelUp is not a GameINstance Member

### ISSUE THREAD

**Issue by RyanMesser** [maximegmd/CyberEngineTweaks#862]
Running Game.LevelUp() returns

sol: runtime error: [string "Game.LevelUp()"]:1: Function LevelUp is not a GameInstance member and is not a global.
stack traceback:
	[C]: in function '__index'
	[string "Game.LevelUp()"]:1: in main chunk

**Comment by WSSDude** [comment]
Developer functions were removed by CDPR this is one of them.
