### ISSUE TITLE
Crash on newest driver

### ISSUE THREAD

**Issue by homizu2** [maximegmd/CyberEngineTweaks#868]
on RTX 3060 laptop GPU, 537.42 driver was installed.

Without CET: Game works.
With CET: Game crashes.

537.34:
Without CET: Game works.
With CET: Game works.

Willing to test and provide a log if needed.

**Comment by WSSDude** [comment]
Let it crash and make a report with crash reporter. **Dont send the report!** 

After this, please navigate to this folder (open Windows Explorer and paste this into path field)
%LocalAppData%\REDEngine\ReportQueue

Package latest report folder there and post it here if you can (there should be no sensitive info if you are worried about that, just snapshot from crash and some info about loaded modules, so I can look where it died and what modules were active).

Also post your CET log file I guess, although I doubt it'll have any information...

**Comment by WSSDude** [comment]
Oh right, would also be nice to know OS I guess, didnt mention that.

**Comment by homizu2** [comment]
I solved the issue, thank you. There is no need for a report. Let me report my findings.

I downloaded the game using OFFLINE gog installers and played the game offline.
I replaced Galaxy64.dll and GOGservices dll with unofficial patches and the game is working fine.

I am on windows 11 professional edition. 
Thank you! There seems to be no issue for now. If there is, I will update this thread later!

**Comment by homizu2** [comment]
However, if next time I can see this issue, I might report it again-when the game updates. thanks

**Comment by homizu2** [comment]
I don't know if the other issues mentioned above used a GOG copy of the game. If yes, it could be the issue with GOG dlls interacting with CET-not sure
