### ISSUE TITLE
getting stuck in bind section of CET

### ISSUE THREAD

**Issue by Floriu** [maximegmd/CyberEngineTweaks#869]
i can´t bind any key when i start game with CET, i get stuck at binding but nothing happens, any ideas how could i solve that?

**Comment by ParaNada-666** [comment]
I was stuck on the same issue. Currently I have not updated to Cyberpunk 2077 2.0 but was using the latest CET version. Don't know if that is that issue but I went and got the last release for CET
 ( https://github.com/maximegmd/CyberEngineTweaks/releasesDont/tag/v1.25.2 ). 
Dropped the Zip on Vortex and walla I got CET widow pop up. Hope that helps

**Comment by WSSDude** [comment]
For issues with setup, go onto our Discord. This is for bugs and such with CET, this is a setup issue.

**Comment by Floriu** [comment]
> For issues with setup, go onto our Discord linked in Readme. This is for bugs and such with CET, this is a setup issue.


ok sorry i thought it was a bug i was on discord too
