### ISSUE TITLE
SetDebugFact Error

### ISSUE THREAD

**Issue by Aiden-Potter** [maximegmd/CyberEngineTweaks#870]
![image](https://github.com/maximegmd/CyberEngineTweaks/assets/43874834/095059c1-b1d1-4c11-9f9a-50a8ceffc603)

Command AddToInventory work well，but SetDebugFact Error

**Comment by edgarwch** [comment]
and command AddDebugFact got same error

**Comment by Aiden-Potter** [comment]
I do not know the reason why cdpr employee changes the secret ending's unlock condition, but it really give me a big shock. Thank you,cdpr!

**Comment by maximegmd** [comment]
Command removed by CDPR
