### ISSUE TITLE
Game.GiveDevPoints and Game.SetDebugFact commands not working.

### ISSUE THREAD

**Issue by Diavol0o** [maximegmd/CyberEngineTweaks#871]
The console says:

sol: runtime error: [string "Game.SetDebugFact("sq032_johnny_friend", 1)"]:1: Function SetDebugFact is not a GameInstance member and is not a global.
stack traceback:
	[C]: in function '__index'
        [string "Game.SetDebugFact("sq032_johnny_friend", 1)"]:1: in main chunk

and

sol: runtime error: [string "Game.GiveDevPoints("Primary", 10)"]:1: Function GiveDevPoints is not a GameInstance member and is not a global.
stack traceback:
	[C]: in function '__index'
	[string "Game.SetDebugFact("sq032_johnny_friend", 1)"]:1: in main chunk

**Comment by yzprofile** [comment]
Game.GetQuestsSystem():SetFactStr("sq032_johnny_friend", 1)
