### ISSUE TITLE
secret ending command

### ISSUE THREAD

**Issue by Vandergrift** [maximegmd/CyberEngineTweaks#873]
Hi can someone tell what is the command for secret ending since the old one doesnt work anymore. Its my fourth playthrough and i still cant get that secret ending to trigger, i alway have something around 85% and do the quest and choose dialogues but i dont even have same options as people in guides because im already frien with Johnny. Is there a new command?

**Comment by maximegmd** [comment]
Not the place for this kind of question

**Comment by Vandergrift** [comment]
So where i should ask for fix/ new command for CyberEngineTweaks?
