### ISSUE TITLE
Please answer before you close. Ty

### ISSUE THREAD

**Issue by IsraelSnow** [maximegmd/CyberEngineTweaks#875]
I think I have it installed correctly. I’ve tried punching it in multiple different ways multiple different codes and the only one I was ever able to get to work with the ad money. Please see attached picture for the errors I am getting.
![IMG_7470](https://github.com/maximegmd/CyberEngineTweaks/assets/146654570/f4f7440f-d81f-4bfd-ac3c-99da424b910d)

**Comment by maximegmd** [comment]
I will now ban everyone who asks dumb questions on github, github is for technical discussion.
