### ISSUE TITLE
Some mods not working. "sol: file error: cannot open init.lua: No such file or directory" in mod logs. 

### ISSUE THREAD

**Issue by Vertrixx** [maximegmd/CyberEngineTweaks#876]
# Bug

Operating system: Windows 10 Home 
Game version: 2.0PL
CET version: 1.26.1
GPU: RTX 3080ti FE

## Description

Multiple mods that depend on CET (Car modification shop, AppearanceMenuMod, AppearanceChangeUnlocker) have stopped working (with no other changes, Car mod shop was working fine a couple days ago then stopped working suddenly). They first show as loaded in the console, but do not work ingame. AMM and ACU still function on initial launch, but when I reload all mods AMM completely stops working. When I reload all mods those mods fail to load. This shows up in all of their respective logs at the time of reload: 

"sol: file error: cannot open init.lua: No such file or directory"

These mods all still have the init.lua file in their respective directories, but it seems CET cannot find those files. 

What's strange is that _some_ mods (smartWindow, Authentic Shift Audio Gear Ratios, E3_StarterCar, etc) work just fine, without that error.

## Expected behaviour

All mods to load and function in game. No failing to load on 'reload all mods' and no failure to locate init.lua for those 'failed to load' mods.

## Reproduction

Unable to find reproduction method.

Logs:

[scripting.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782657/scripting.log)

[AppearanceMenuMod.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782648/AppearanceMenuMod.log)
[AppearanceChangeUnlocker.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782650/AppearanceChangeUnlocker.log)
[Car Mod Shop.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782654/Car.Mod.Shop.log)

[Authentic Shift Audio Gear Ratios.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782671/Authentic.Shift.Audio.Gear.Ratios.log)
[CET_player_underwear_removal_extended.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782672/CET_player_underwear_removal_extended.log)
[E3_StarterCar.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782674/E3_StarterCar.log)
[smartWindow.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782675/smartWindow.log)
[ZKVTD.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782676/ZKVTD.log)
[nativeSettings.log](https://github.com/maximegmd/CyberEngineTweaks/files/12782679/nativeSettings.log)

**Comment by WSSDude** [comment]
Well you would want too much from us ;)

Mods need to get updated, be patient. This has not much with CET other than it broke with update (which pretty much everything did)

**Comment by Vertrixx** [comment]
> Well you would want too much from us ;)
> 
> Mods need to get updated, be patient. This has not much with CET other than it broke with update (which pretty much everything did)

My apologies. I didn't mean to come across like I want it all fixed instantly or anything like that. I just want to figure out the problem. Everything pointed me towards CET not reading the filepath properly or something like that, so I raised an issue here. 

All of the mods I listed are updated for the latest version of the game and CET, so I really don't know what's causing them to not load. 

Would you have any idea or clue what the problem is? It's fine if not, but I wanna try troubleshoot this at least.

**Comment by WSSDude** [comment]
CET has issues with soft links, hard links should work (in case you use Vortex). MO2 has some virtual filesystem CET cant work with at all atm (there should be some ticket about this soon, was discussed on Discord recently).

Best way to install and use CET mods is manual install tbh, is easy to update and cleanup the mods manually. Mod managers are a bit pain with CET.

**Comment by WSSDude** [comment]
Other than that, no pathing related issues comes to mind.

**Comment by Vertrixx** [comment]
> CET has issues with soft links, hard links should work (in case you use Vortex). MO2 has some virtual filesystem CET cant work with at all atm when mod requires write permissions (which are majority of popular mods... there should be some ticket about this soon, was discussed on Discord recently).
> 
> Best way to install and use CET mods is manual install tbh, is easy to update and cleanup the mods manually. Mod managers are a bit pain with CET.

Okay, so to explain a bit for my installation: I use MO2 for mods that don't require CET or Redscript (Archive mods work fine with MO2). For dependencies, I installed them manually. All CET and Redscript mods I installed manually as well. 

I'm using the "Mod remover" bat file and reinstalling CET and dependencies from scratch, then testing each mod one by one. Hopefully that fixes it, but if not then I'll reply again to update.

If that doesn't work, then I'll try that root folder setup that people used to make CET work with MO2. 

I don't have a clue how this issue even came about. Car mod shop was working one night, then not the next day with 0 changes. Then new CET mods wouldn't work after that (init.lua can't be found for all of them) even though they're all manually installed and I can see the lua file in their folders. It's so confusing that some mods work just fine but others can't be found. 

Have there been any other issues like this in the past? I saw that having lua installed on windows could cause issues, but I don't have it installed and also saw that an update was pushed to fix that.

**Comment by Vertrixx** [comment]
Okay, I've tested it some more and it seems that it's not _every_ new mod. 

![image](https://github.com/maximegmd/CyberEngineTweaks/assets/20017231/5961ff81-d394-4c51-be18-5fa1825875d2)

I added flashlight, sitanywhere, and radioext. Out of those mods, radioext still works even with the other new mods not working. So now I'm a bit more confused, because the mod author of car mod shop didn't know how to solve this issue with his mod. It's clearly not a CET issue, but one for the mod authors of those mods. 

I'll have to talk to the mod authors to figure out what the problem is with their mods specifically. Maybe once everything is updated for 2.1 (whenever that comes out) it'll be fixed, but until then I'll try to find out what's going on to make these init.lua files unreadable.

**Comment by Vertrixx** [comment]
Okay, full manual install fixed it.

@WSSDude What you said about MO2 was completely right. It's so bad for Cyberpunk. The overwrite folder was messing things up, after a bit of trial and error I identified that as the main problem and did a full manual install of my mods.

Now it all works well. Thank you for your help :D

**Comment by WSSDude** [comment]
#877 😉

**Comment by WSSDude** [comment]
Should help when it will be merged I hope.

**Comment by ChaosAndCoffee** [comment]
Just as a quick side note/warning to anyone wanting to use MO2 later if the commit is added (I have a working install of MO2 for CP, currently you need to use Rootbuilder for almost everything and somewhat jank setup required), the above fix/commit will make everything work (I helped test it) aside from CET & red4ext. Those two will still need to be installed with Rootbuilder on MO2, but everything else will install normally and no complex setup required.

Hoping and eagerly awaiting the approval and addition of the commit so I can continue to use MO2 _and_ not have to use the jank setup in the future. God I hate manual modding. Also huge thanks to anyone working on CET.
