### ISSUE TITLE
Game.AddDebugFact in being shown in documentation, but is not a GameInstance member and is not a global.

### ISSUE THREAD

**Issue by BitKovin** [maximegmd/CyberEngineTweaks#881]
this command is first on [global functions page](https://wiki.redmodding.org/cyber-engine-tweaks/functions/global), but in game attempt to execute it results error:

sol: runtime error: [string "Game.SetDebugFact("sq032_johnny_friend", 1)"]:1: Function SetDebugFact is not a GameInstance member and is not a global.
[C]: in function '__index'
[string "Game.SetDebugFact("sq032_johnny_friend", 1)"]:1: in main chunk

**Comment by maximegmd** [comment]
Yes we need to update the wiki, this function doesn't work like this anymore, you can around on discord for the correct function use.
