### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by Nervnetduknecht** [maximegmd/CyberEngineTweaks#886]
# Bug

Operating system: Windows 11 (Build 22621.2428)
Game version: 2.01
CET version: 1.27.1
GPU: RTX 3080

## Description

CET has a memory leak problem, can be fixed by pressing reload mods (i have all mods deactivate for exclude a cet mod).
Only if Raytracing is activated.

## Expected behaviour

It's stutter like a heartbeat

## Reproduction

It's beginning to stutter when I open the menu and stay in it longer.

**Comment by WSSDude** [comment]
Its a problem of a mod not releasing resources priperly, reload mods releases all mods resources. You just confirmed it is not a CET issue.
