### ISSUE TITLE
Error: Not a GameInstance...

### ISSUE THREAD

**Issue by JJ-Campbell** [maximegmd/CyberEngineTweaks#903]
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: Windows 10 Ver 22H2 Build 19045-3570
Game version: Phantom Liberty - Patch 2.02
CET version: 1.28.1
GPU: NVIDIA GeForce RTX 3070

## Description

Write here a description of the issue.
I get this error when executing a command: ModStatPlayer is not a GameInstance member and is not a global. See attached screen capture.
[config.json](https://github.com/maximegmd/CyberEngineTweaks/files/13326255/config.json)
[cyber_engine_tweaks.log](https://github.com/maximegmd/CyberEngineTweaks/files/13326256/cyber_engine_tweaks.log)
[scripting.log](https://github.com/maximegmd/CyberEngineTweaks/files/13326257/scripting.log)
![Error](https://github.com/maximegmd/CyberEngineTweaks/assets/150548428/66acafa2-234b-48c4-b449-44ce2af87d05)

## Expected behaviour

Write here what you expect to happen instead.

## Reproduction

Write here step by step how to reproduce the issue if applicable.

**Comment by maximegmd** [comment]
Game functions changed after v2

**Comment by JJ-Campbell** [comment]
Where is there a good place to get the current game functions?  Google only seems to return the out-of-date functions.  It should be mandatory that all Webpages have dates.  Just saying...

**Comment by maximegmd** [comment]
It should also be mandatory to respect proper opensource etiquette and understand that maintainers are doing this on their free time and that you should be thankful for what we have so far. If you have issues with the documentation, everything is opensource and we accept contributions.

**Comment by PicoJr** [comment]
It seems it is possible to achieve the same result as `Game.ModStatPlayer` with the following code:

```lua
StatValue = 500;
StatType = 'CarryCapacity';
PID = Game.GetPlayer():GetEntityID();
SS = Game.GetStatsSystem();
currValue = SS:GetStatValue(PID, StatType)
print(" -  Current  [  "..StatType.. "  ]  value: "..string.format("%f", currValue))

if currValue == StatValue then
    print(" -  "..StatType.." is already "..StatValue..", no need to edit. \n ")
else
    statMOD = Game['gameRPGManager::CreateStatModifier;gamedataStatTypegameStatModifierTypeFloat'](StatType, 'Additive', StatValue);
    SS:RemoveAllModifiers(PID, StatType, true)
    SS:AddSavedModifier(PID, statMOD)
    print(" -  [ "..StatType.." ]  SETTED TO :  "..string.format("%f", StatValue).." \n ")
end
```

The original poster (not me) provided a one-liner (cf source below).

[source/credit](https://www.nexusmods.com/cyberpunk2077/mods/9247?tab=posts): <https://www.nexusmods.com/cyberpunk2077/mods/9247?tab=posts>

I only tested with `StatType = "Memory"` so far, I don't know if it persists after saving.

My cyber_engine_tweaks.log indicates:

```
CET version v1.35.1 [HEAD]
Game version 3.0.78.57301
```

I am running Cyberpunk 2077 via Proton on Linux.
