### ISSUE TITLE
TweakDB:CloneRecord("newname", "Items.Preset_Knife_Default") doesnt copy throwable projectile

### ISSUE THREAD

**Issue by tuffgamer** [maximegmd/CyberEngineTweaks#904]
# Bug

Operating system: Windows 10
Game version: 2.02
CET version: 1.28.1
GPU: 3070ti

## Description

It looks like this command 

"TweakDB:CloneRecord"

doesnt clone knife records properly because cloned knifes are not throwable.

Probably projectile template for those items is missing so it couses that cloned Knifes items records doesnt works properly.

## Expected behaviour

Cloned Knife items can be throwable.

## Reproduction

Clone "Items.Preset_Knife_Default", add it to inventory, equip cloned item and try to throw it.

**Comment by WSSDude** [comment]
If this is still an issue on latest CET version, feel free to reopen.

But I think you may just not be using it right, our Discord server should be a better place to confirm if this is a bug and what may be wrong, could be just usage issue.
