### ISSUE TITLE
help/doubt about Game.GetPreventionSpawnSystem()

### ISSUE THREAD

**Issue by hxsgame** [maximegmd/CyberEngineTweaks#906]
Please...Encountered some problems when using the function "Game.GetPreventionSpawnSystem():RequestUnitSpawn()"
seeking advice...
1, The past return value of this function was the type of "EntityID", but in 2.0+, the return value change to "Uint32"...What does this return mean?
2,  How do I delete the SpawnsNPCs ?
I try to use "Game.GetPreventionSpawnSystem():RequestDespawn()" \ "Game.GetPreventionSpawnSystem():CancelSpawnRequest()", But none of them had any effect...Has these functions not been implemented yet?
Please...help me...

**Comment by WSSDude** [comment]
Discord linked in the readme is a place for these, this is not the place. This is for bug reports.
