### ISSUE TITLE
Importing lua module using local

### ISSUE THREAD

**Issue by teleprint-me** [maximegmd/CyberEngineTweaks#907]
# Bug

![Screenshot from 2023-12-05 17-47-32](https://github.com/maximegmd/CyberEngineTweaks/assets/77757836/e2512846-ee06-4988-bf33-8efc2302ca3a)

Operating system: Linux
Game version: 2.1
CET version: 1.29.0
GPU: AMD RX 580

## Description

CET fails to load `json` within the modules local scope.

## Expected behavior

I expect CET to load the Test module successfully, similarly to what `lua` would output.

```sh
Attempting to load JSON module...
JSON module loaded successfully.
Encoded result: {"Test":"Value"}
```

## Reproduction

1. Create a module within the `cyber_engine_tweaks/mods` path.
2. Create a `init.lua` script.

The structure of the `mod/Test`:

```sh
17:44:36 | ~/.local/share/Steam/steamapps/common/Cyberpunk 2077/bin/x64/plugins/cyber_engine_tweaks
  λ tree mods/Test
mods/Test
├── db.sqlite3
├── init.lua
├── Modules
│   └── json.lua
└── Test.log

2 directories, 4 files
```

3. Populate the module with a test script.

```lua
print("Attempting to load JSON module...")
local status, json = pcall(require, "Modules.json")

if not status then
    print("Failed to load json module with error: " .. tostring(json))
else
    print("JSON module loaded successfully.")
    local result = json.encode({["Test"] = "Value"})
    print("Encoded result: " .. tostring(result))
end
```

4. Run Cyberpunk 2077 and view the console to see the status.

Note: `Modules/json.lua` is an exact 1:1 copy of `scripts/json/json.lua` and I tested both paths to see if the behavior was consistent and it was consistent.

**Comment by WSSDude** [comment]
json.lua is included by CET already under `json`, I suppose you get that error because of that... Just try to use packaged json.lua, no need to require or include anything, use `json.xxx` directly.

**Comment by WSSDude** [comment]
I believe this is an user error so closing this... As there are mods using json.lua without issues, I bet the issue comes from you trying to require it for whatever reason when it already is required for you implicitly...

**Comment by teleprint-me** [comment]
> json.lua is included by CET already under `json`, I suppose you get that error because of that... Just try to use packaged json.lua, no need to require or include anything, use `json.xxx` directly without requires and such.

I did do that. The issue was consistent as I noted in my original post. That's Did why I attempted with a separate module. Did you attempt to reproduce?
