### ISSUE TITLE
Cyberpunl 2077

### ISSUE THREAD

**Issue by JohnnyToon** [maximegmd/CyberEngineTweaks#908]
CET binding file missing.

Operating system: SteamOS (Steamdeck)
Game version: Steam version
CET version: cet 1.29.1
GPU: RDNA 2.0

## Description

hello im a steamdeck user since i dont have a pc this is how im able.to play cp2077 with mods, i have an issue that due to the fact that i deleted the binding file to allows me to bind a key whenever i install , deleting and reinstall newer versions CET (or the version of the one ideleted the file) the binding file is missing thus preventing to bind any key. If i remember correctly there used to be older versions of CET that had this file. Is there any way i can recup the file?? Or link to an older CET that has the file.in it ? 

Here a some screenshot:
![1702409584710725758282971640774](https://github.com/maximegmd/CyberEngineTweaks/assets/121589302/bda80595-74d9-44da-93b7-f5e105e3d3e7)

![17024096281933745680029857355311](https://github.com/maximegmd/CyberEngineTweaks/assets/121589302/e69622b9-f4df-4bc6-b709-724908b7c6fe)

**Comment by maximegmd** [comment]
Support request go on discord
