### ISSUE TITLE
CET DOESN'T OPEN WITH SPAWNED COMPANIONS AFTER COMBAT

### ISSUE THREAD

**Issue by overself1** [maximegmd/CyberEngineTweaks#913]
Hi,

I'm having an issue that's driving me crazy.
I'm playing with companions spawned with AMM. When I start the game, CET opens and works fine as long as I'm not shooting in combat.When I fineshed the combat and try to open it again, it doesn't! I have to reestart the game for the overlay works again so I can open CET.
My last playthrough I played with companions too and it didn't happened. I even installed an older version of AMM and nothing, the issue was still there.
Does anybody please know how to fix it??

**Comment by WSSDude** [comment]
This is some other mod issue, you mentioned AMM... Reports are made with just clean CET... And only for real issues, this is not support channel... Go on Discord linked in the readms.
