### ISSUE TITLE
Creates stutters

### ISSUE THREAD

**Issue by DoganM95** [maximegmd/CyberEngineTweaks#914]
# Bug

Operating system: Win 11
Game version: 2.1
CET version: 2.1 hotfix
GPU: AMD 7900xtx

## Description

Played 50h and decided to add mods, including CET. This however, added stuttering to the game, which happen like every 0.5s. 
Removed all texture mods, scripts, etc and left only the basics (Redscript, RED4ext, CET) wiith stutters persisting.
After removing CET, the stuttering was completely gone (Redstuff is still installed), so CET seems like the cause of the stuttering.
The fps itself does not drop noticably.

## Expected behaviour

Logically, after installing CET, the game should not start to stutter every 0.5s.

## Reproduction

- Install Redscript
- Install RED4ext
- Install CET
- Run the game (resume)
- Rotate the camera (using a controller, to get a constant volocity) and notice the stutters
- Remove CET, run the game again
- Rotate again and see the stutters vanish

**Comment by WSSDude** [comment]
Ask for support on linked Discord, this is not proper report. Reports are made with just CET. Even if you had other things you mentioned disabled,  you likely still have some mod active, they'll help you find what is going on. Clean CET is unlikely to produce these issues. Simple menu was linked to stutters with CET for example. 

They should provide you with required support.
