### ISSUE TITLE
JournalManager.GetContacts should accept two parameters

### ISSUE THREAD

**Issue by DVLP** [maximegmd/CyberEngineTweaks#918]
# Bug

Operating system: Windows
Game version: 2.1
CET version: v1.29.1
GPU: -

## Description

JournalManager.GetContacts() should accept 2 parameters but it's throwing an error in logs
[2024-01-28 22:23:41 UTC+00:00] [13412] ...weaks\mods\make_a_living__courier\modules\Panopticon.lua:76: Function 'GetContacts' requires 1 parameter(s).

## Expected behaviour

It should not throw an error

## Reproduction

```
Override("JournalManager", "GetContacts", function(this, journalRef, entries, wrapped)
        wrapped(journalRef, entries)
    end)

```

**Comment by WSSDude** [comment]
If you can replicate this on latest CET release, feel free to reopen. But I would not be so sure it has 2 params tbh when the parser writes it has one, could have changed between updates.

If it is still an issue, we can try to have a look I guess. But my personal guess is that either sth changed with the update or you are trying to pass self explicitly.

**Comment by DVLP** [comment]
Makes sense. Once I'll be developing a new mission I'll confirm this
