### ISSUE TITLE
 Is there a command to view previous subtitle lines (dialogue log) to avoid missing anything?

### ISSUE THREAD

**Issue by 4Brad-23** [maximegmd/CyberEngineTweaks#922]
[Like in GTAV](https://i.imgur.com/b5dMntA.jpghttps://i.imgur.com/b5dMntA.jpg) and a mod in [The Witcher 3](https://www.nexusmods.com/witcher3/mods/5548)

Thanks really appreciate the effort.

**Comment by maximegmd** [comment]
Unrelated to the mod.

**Comment by 4Brad-23** [comment]
> Unrelated to the mod.

It is, but sure.

**Comment by maximegmd** [comment]
It isn't.
