### ISSUE TITLE
No Intro Videos crashes, no other mods

### ISSUE THREAD

**Issue by jabcreations** [maximegmd/CyberEngineTweaks#923]
# Bug
Simple: I wanted to not have to watch the videos and press the spacebar numerous times just to start playing so I got this mod:

https://www.nexusmods.com/cyberpunk2077/mods/533?tab=description

I purchased the base game plus the expansion pack packaged as one. Installed that mod and eventually installed CyberEngineTweaks.

I then removed the skip videos mod, had GOG verify the install files, reinstalled CyberEngineTweaks and it no longer crashes. So that is my confirmation. If there is another way to automatically skip videos I'm open to it. I consider this report in the "nice-to-have" category.

**Comment by sb0** [comment]
Hi there.

That mod does not require Cyber Engine Tweaks. So opening an issue here I don't think will help you.
Please post on nexus forum for this issue.
