### ISSUE TITLE
Update description and Nexusmods page to have RED4ext as a dependency from now on

### ISSUE THREAD

**Issue by breadland** [maximegmd/CyberEngineTweaks#925]
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: Windows 11 Pro 23H2
Game version: 2.12
CET version: 1.31.1-yawn
GPU: AMD RX 6800XT

## Description

The new version of CET that supports Cyberpunk 2.12 now requires RED4ext to be installed. Without it the mod won't run at all. No overlay, no logs. Despite being on a clean install, with absolutely no leftover files from a previous CET version.

Previous versions ran fine without any other dependencies and since there was no information on the readme, Nexusmods description & popup for "Additional files required" for this version, I had no idea it was now required for it to work.

## Expected behaviour

Add an info in the description for this release that RED4ext is required for the mod to run. Also add RED4ext as a required file on the Nexusmods page.
Also update the Cyber Engine Tweaks wiki to list it as a dependency.

## Reproduction

Fresh install of Cyberpunk 2077 2.12.
Download latest CET release, 1.31.1-yawn
Drag n drop to game directory. CET will now not run despite not having any files from the older versions, like cyber_engine_tweaks.asi

**Comment by KaYBlitZ** [comment]
Thanks for posting this. The new release made it seem like I cant read. But nowhere did it say we needed to delete a file. Couldnt find it in the wiki either. Anyways deleting that file (or any leftover files for that matter) still didnt work like you mentioned. This has always been drag and drop for me, which the wiki implies as well. Let me see if installing RED4ext solves it for me.

**Comment by KaYBlitZ** [comment]
Can confirm it works. Downloaded latest red4ext here (non-pdbs version): https://github.com/WopsS/RED4ext/releases . Extract that first to cyberpunk root installation before extracting cyber engine tweaks to same cyberpunk root. Everything should work now

**Comment by maximegmd** [comment]
It's fixed :)
