### ISSUE TITLE
CET 1.31.2: exEntitySpawner.Spawn() and exEntitySpawner.SpawnRecord() crash the game v2.12 

### ISSUE THREAD

**Issue by anygoodname** [maximegmd/CyberEngineTweaks#928]
Any attempt to spawn anything using exEntitySpawner crashes the game.

**Comment by Janenxxx** [comment]
The game always crashes when I try to open CET in game but not while outside the game in the main menu

**Comment by anygoodname** [comment]
Splendid!
Thank you very much :)
