### ISSUE TITLE
CET crashes game

### ISSUE THREAD

**Issue by Janenxxx** [maximegmd/CyberEngineTweaks#929]
I try to open CET latest version 1.31.2 and the game crashes while I am in the game but it works while in the main menu.

**Comment by Janenxxx** [comment]
I tried to delete the CET file in the Red4ext file and the game ran smooth but I wasn't able to open the menu but when I try to open the CET menu in game it crashes immediately. It would be nice if there would be a solution for this please and thank you.

**Comment by maximegmd** [comment]
Fixed in 1.31.3
