### ISSUE TITLE
Latest release contains a trojen?

### ISSUE THREAD

**Issue by theghostglitch** [maximegmd/CyberEngineTweaks#932]
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: Windows 11
Game version: 2.12
CET version: 1.31.2
GPU: GTX 1060 TI

## Description

Windows Defender flaged cyber_engine_tweaks.dll as a trojen.Trojan:Win32/Wacatac.B!ml specifically.

## Expected behaviour

To not get a virus? I think this is a given?

## Reproduction

Scan cyber_engine_tweaks.dll with a virus scanner....
![ApplicationFrameHost_Q1uKBvKOF5](https://github.com/maximegmd/CyberEngineTweaks/assets/86519581/12afd93b-e45e-46a6-8470-b8cfcfa56a10)

**Comment by Ineptus** [comment]
False alarm. It's a good practice to always use Google before you write or say something new. This helps avoid spreading false information or, at least, may ensure correct spelling/pronunciation. 
E.g. [https://www.reddit.com/…/trojanwin32wacatacbml/](https://www.reddit.com/r/antivirus/comments/p2o2yj/trojanwin32wacatacbml/)

**Comment by theghostglitch** [comment]
Yeah. False alarm, but still an issue. People trust anti-virus software over random things they download. Even if it's open source. There are ways of programming things that don't set off anti-virus alerts. Hence the dev removing the piggyback hook with red4ext which caused the alert. And don't get me started on grammer policing.
