### ISSUE TITLE
Virus detected. Don't close this.

### ISSUE THREAD

**Issue by theghostglitch** [maximegmd/CyberEngineTweaks#933]
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: Windows 11
Game version: 2.12
CET version: 1.31.0 - 1.32.2
GPU: 

## Description

There is a virus in cyber_engine_tweaks.dll 
Sorry, had no choice but to report this to github due to my previous issue being immediately closed a removed.
Shameful action.....

## Expected behaviour

Remove the virus.

## Reproduction

Scan cyber_engine_tweaks.dll with a virus scanner.

**Comment by maximegmd** [comment]
The mod is opensource, the zip is from the build pipeline, don't be an idiot.
