### ISSUE TITLE
CET 1.32.0 - any attempt to use exEntitySpawner.Spawn() results in CET error and application close.

### ISSUE THREAD

**Issue by anygoodname** [maximegmd/CyberEngineTweaks#937]
Hello,

similar to the CET 1.31.0, using exEntitySpawner causes issues - an error message and application close.
Screenshot attached.

regards.
![Screenshot (6566)](https://github.com/maximegmd/CyberEngineTweaks/assets/89723772/223962e3-f7ae-4bcd-afd3-3431a74d8316)

**Comment by Janenxxx** [comment]
I got the same issue

**Comment by LBDBK** [comment]
Right, from my 68 CET mods i manage to narrow it down to only 3 that breaks CET in the end and those are:
AMM
Entity Spawner
E3 Smart Window

**Comment by turbolul** [comment]
I have the same issue, all mods updated game as well

**Comment by anygoodname** [comment]
Fixed in the 1.32.1 as stated. Thanks a lot :)
