### ISSUE TITLE
cyber engine tweaks failed to resolve adress for hash 0x1817231d. Process will now close.

### ISSUE THREAD

**Issue by DenouementEfflorescence** [maximegmd/CyberEngineTweaks#944]
I have tried to install cyber engine tweaks to install some car mods. everytime i try to install it, with vortex or manually, i get this error.

# Bug

Operating system: Windows 11
Game version: 2.12
CET version: 1.32.2
GPU: RTX 3070

**Comment by DenouementEfflorescence** [comment]
um and how exactly is this completed???

**Comment by maximegmd** [comment]
This isn't a bug, this is misuse, support requests are redirected to discord.

**Comment by tianhuahao** [comment]
https://www.youtube.com/watch?v=Rfme1bc7C78

**Comment by DenouementEfflorescence** [comment]
> https://www.youtube.com/watch?v=Rfme1bc7C78

Thx i appreciate it
