### ISSUE TITLE
Failed to resolve adress !

### ISSUE THREAD

**Issue by Alphoxii** [maximegmd/CyberEngineTweaks#945]
Hi ! 
I have an issue with CyberEngineTweaks , after installing it when i try to launch the game it says " Cyber Engine Tweaks Failed to resolve adress dor hash 0x1917231d. Process will now close"

i tried downloading another version but it didn't change anything , if someone has any idea what the probleme is ? 

I have a 2.1 version of the game ! 
Thanx for reading me :) 

![Screenshot 2024-05-03 182921](https://github.com/maximegmd/CyberEngineTweaks/assets/92804953/580ecbfb-1e4d-4342-9b28-005d1a689794)

**Comment by refriedfood** [comment]
Same issue:

![alt text](https://ptpimg.me/9315hw.png)

What's the fix?
