### ISSUE TITLE
bug with 1.32.3

### ISSUE THREAD

**Issue by SpiderMonkey314159** [maximegmd/CyberEngineTweaks#953]
# Bug

Operating system: PC 
Game version:  Phantom Liberty 
CET version: 1.32.3
GPU: GEForce RTX 4090

## Description

When I upgraded from 1.32.2 to 1.32.3 and the mods menu disappeared from the game.  Also, some mods (like night vision) no longer worked, and my key binding to bring up CET no longer worked.  Reverting to 1.32.2 corrected the issues. 

## Expected behaviour

Write here what you expect to happen instead.

## Reproduction

Write here step by step how to reproduce the issue if applicable.

**Comment by WSSDude** [comment]
Download latwst VC redist, you probably have outdated one.

Download abd install both of these, reopen in case it doesnt help.

https://aka.ms/vs/17/release/vc_redist.x86.exe
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by WSSDude** [comment]
CET always uses latest VC2022 runtime when it gets updated so first thing to try is definitely installijg newer redist.
