### ISSUE TITLE
Bug with the newest Version 1.32.3

### ISSUE THREAD

**Issue by Nicewar23** [maximegmd/CyberEngineTweaks#956]
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: Windows 10 Pro
Game version: 2.12
CET version: 1.32.3
GPU: Geforce RTX 4080

## Description

Everytime I try to start the game a Pop up comes up and tells me "Failed to resolve Address for hash 0x9ccf1543. Process will now close."
And as it told me it shuts the Game down

**And of course i updated every single Mod**

## Expected behaviour

Should Start the game I guess

## Reproduction

Updated from a CET Version from around January/February 1.29.1 to the newest from July 1.32.3 and then it started
![grafik](https://github.com/user-attachments/assets/14b4751b-cbec-4a66-9d74-62d600df51a4)

**Comment by WSSDude** [comment]
Buy the game, then cry

**Comment by Nicewar23** [comment]
I did buy it on GOG from my Dad's account and i used it since 2020 couse GOG said that they support that

**Comment by WSSDude** [comment]
Error says otherwise, is either not original not latest version.

Anyway no further support here, this is for CET issue and this is not an issue on legal fully updated copy.

**Comment by Nicewar23** [comment]
Okay sorry for wasting your time gotta look at it with gog since I did buy it

**Comment by TypicalTv** [comment]
I do have the same issue and I got it off of steam and it's legit. This could happen to anyone and its not just because u have a pirated game. I'm on the latest version of cyberpunk 2077 and I continue to receive this error.
