### ISSUE TITLE
Version v1.32.3 doesn't work in a fresh Windows installation and plain Cyberpunk

### ISSUE THREAD

**Issue by DVLP** [maximegmd/CyberEngineTweaks#959]
**Read the first comment first. The link to VC Redist must be updated.**

# Bug

Operating system: Windows 10
Game version: 2.12
CET version: v1.32.3
GPU: 1080TI

## Description

Just installed Cyberpunk on a fresh Windows installation and added CET version v1.32.3
The overlay doesn't show(I installed redist and restarted my computer). Then I tried version v1.32.2 and the overlay did show. Then again version v1.32.3 and it stopped showing again. This is a clean Cyberpunk installation without Redmod or any other mods/plugins.

btw main .log file is not created so it doesn't launch

## Expected behaviour

Overlay to show

## Reproduction

Install Cyberpunk with no other mods in a fresh Windows 10 installation with VCRedist, then add CET v1.32.3 to Cyberpunk. Verify with v1.32.2 that otherwise CET works.

**Comment by DVLP** [comment]
The instructions say to download VC Redist but the link provided here https://wiki.redmodding.org/cyber-engine-tweaks/getting-started/installing is only up to 2019 version. Installing VC Redist with up to 2022 solves the problem. The bug is still open

**Comment by WSSDude** [comment]
Wiki is not ours Not our problem. Wiki is maintained by people on Discord. This is for bugs, issues, sane requests for enhancement... Not problems with either Wiki or usage...
