### ISSUE TITLE
cyber engine tweaks failed to resolve address 0x9ccf1543

### ISSUE THREAD

**Issue by Joshynaldo** [maximegmd/CyberEngineTweaks#961]
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: Windows 10
Game version: newest 
CET version: newest tried also .31.3
GPU: 1080ti

## Description
 When I want to start the game this comes up:
 cyber engine tweaks failed to resolve address 0x9ccf1543

## What my problem is

It should start normally.
I tried also with cet and the core mods like rer4ext Archive xl..

**Comment by kamiuu** [comment]
how did you fix it?

**Comment by Joshynaldo** [comment]
I reinstalled the newest version and checked if Cet has an update

kamiuu ***@***.***> schrieb am Fr., 30. Aug. 2024, 05:44:
