### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by TsengSR** [maximegmd/CyberEngineTweaks#967]
Is this project dead already? My Cyberpunk 2077 2.13 keeps crashing the instant after the logo appears. Where is the new version?

**Comment by maximegmd** [comment]
It was released within hours of 2.13 releasing...

**Comment by TsengSR** [comment]
No. New update came out 2-3 days ago. Still crashes on start after logo. No update yet. Last update 3 weeks ago

**Comment by maximegmd** [comment]
There has been no update since we pushed our latest version : https://steamdb.info/app/1091500/history/

Support requests go through discord, certainly not by asking if the project is dead on github.
