### ISSUE TITLE
Can't Start the game. Error: "Failed to resolve adress for hash 0x1817231d"

### ISSUE THREAD

**Issue by bmq34** [maximegmd/CyberEngineTweaks#968]
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: Win10 pro
Game version: 2.13
CET version: 1.33
GPU: I5-12600k

## Description

As the title says.

## Expected behavior

The game won't start

## Reproduction

Install mod with Vortex -> Start -> Error => No start of the game => Me cry ;_(

**Comment by ahmederaqi95** [comment]
up

**Comment by maximegmd** [comment]
As the first lines of the template state:

> Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

Therefore, you are redirected to the discord for support.
