### ISSUE TITLE
CET makes the game lag while landing shots at enemies/vehicles after 1-2 hours of playtime

### ISSUE THREAD

**Issue by Bluuwolfly** [maximegmd/CyberEngineTweaks#969]
Essentially title,CET makes the game lag while landing shots at enemies/vehicles after 1-2 hours of playtime

Operating system: Windows 10 Pro 64-bit
Game version: 2.13
CET version: 1.33.0
GPU: Radeon(TM) RX 470 Graphics 8GB VRAM

## Description

The game starts lagging while landing shots at enemies/vehicles (even just corpses) after 1-2 hours of playtime,and I can confirm it's CET doing this as without it,the game doesn't get laggy after 1-2 hours,however,without CET installed,the game's performance overall is worse

## Expected behaviour

No lag while landing shots at enemies/vehicles and corpses

## Reproduction

Play for 1-2 hours without reloading/loading a single save in a single session,the game starts getting worse and worse in performance whenever you land shots on enemies/vehicles and corpses

**Comment by maximegmd** [comment]
Please remove all mods except CET and see if the bug keeps happening.

**Comment by Bluuwolfly** [comment]
It still keeps happening with just CET installed,no other mods
