### ISSUE TITLE
Mod UI's not appearing when bringing down the CET menu

### ISSUE THREAD

**Issue by Porkhammer** [maximegmd/CyberEngineTweaks#971]
I use mods such as Fixer's hidden gems, ping tags enemies etc. Their menus normally appear when I press the keybind to access CET. Then suddenly they do not. I only see the base CET menu with bindings, debug and whatnot.

The CET console tells me that the mods have been successfully loaded. I have reinstalled CET, Native Settings UI, and redscript, along with other mod prerequisites. Still nothing. There is one "error" (red) message in the console, and it reads thusly:

**Function OnSwitchToCredits in class MenuScenario_PauseMenu does not exist**

Why is this happening?

I tried reinstalling CET again but no luck. Managed to pinpoint the error message to SoftCrafting thanks to a couple of helpful individuals in a Cyberpunk discord, but the issue remains. Fixer's hidden gems/Pacifica Typhoon/Ping tags enemies windows still do not appear in CET.

**Comment by WSSDude** [comment]
Its some mod issue, CET by itself doesnt cause this to happen. Some mod probably moves all windows out of view for some reason due to something throwing some exception. 

We have seen similar reports and it was always a mod messing up the state for others. Not much that can be done atm on CET side.
