### ISSUE TITLE
Please add proper Streamline support 

### ISSUE THREAD

**Issue by Rool-IO** [maximegmd/CyberEngineTweaks#976]
When using any Special K version newer than 24.8.11.1, the game will just crash at launch (heap was corrupted according to stacktrace).
Kaldaien says it's due to CET's ImGui code not being compatible with Streamline.

Operating system: Irrelevant 
Game version: 2.13
CET version: Latest
GPU: Nvidia

## Description

Cyberpunk will flatline on startup

## Expected behaviour

Cyberpunk not flatlining and all tools to be properly loaded and working 

## Reproduction

Use any Special K version newer than 24.8.11.1, whatever the injection method.

**Comment by WSSDude** [comment]
Kiero is only used on Windows 7. It does not launch at all normally. If you use Windows 7, you should already have updated anyway to newer version tbh, it is out of support for some time now.

Nobody uses it from us, code was done by some other person.

I consider this invalid tbh but I'll keep it open until kiero is in the source tree...

**Comment by Rool-IO** [comment]
I'm on win11 though

**Comment by WSSDude** [comment]
In that case yeah, this seems like red herring.

**Comment by Rool-IO** [comment]
Sorry about that then

**Comment by WSSDude** [comment]
If you don't mind, I would close this for now. When some more information is found out, we may try to fix it but this is bit of a guessing game atm, we reuse what the game gives us for the majority on supported systems.

We don't hook any DX12 functions ourselves, only game DoPresent function which is called right before DX12 present, we queue our things to render before that. Same for checking for buffer resizes, we use game functions and not DX12.

When it comes to DX12 resources, we grab the game ones again, we are not making our own. That may be an issue I suppose if they wrap the command queue in some way lets say and we effectively call into them indirectly when we queue our things. But unsure what we could do in that case tbh. Is the same thing the game itself uses in the end.

**Comment by Rool-IO** [comment]
I don't mind but I'd be curious to know whether it crashes for you as well if you use any recent SK builds.
I mean if you can repro, that would sure help.. Kal only tried on vanilla so it's pointless for troubleshooting
