### ISSUE TITLE
No prompt for setting Overlay hotkey in 1.34.0 

### ISSUE THREAD

**Issue by joshuabrandes** [maximegmd/CyberEngineTweaks#980]
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: Windows 11
Game version: 2.2 (newest)
CET version: 1.34.0 (newest)
GPU: RTX 4090

## Description

Hi, I did have the Overlay mapped to "Ü" on the German keyboard. But after upgrading to 1.34.0 today the hotkey didn't register anymore. After this **I deleted the bindings JSON and expected to have the initial popup when restarting the game - that didn't happen**.

## Expected behaviour

Wehen there is no bindings JSON the user should be promptet to set a Hotkey upon startup of the game.

## Reproduction

I don't think I have much to add, however I did try disabling the NVIDIA overlay thinking it may interfere, but that didn't fix it...

---
If this isn't an issue with the mod I am really sorry for the inconvenience and please feel free to close this issue if it isn't a bug.

**Comment by joshuabrandes** [comment]
Additional info: updating red4ext to the newest version (v1.26.1) didn't help.

**Comment by WSSDude** [comment]
Ask on Discord linked in readme, there is nothing to do here by us, it works. Is some other issue unrelated to the mod.
