### ISSUE TITLE
Mouse not centered in CET

### ISSUE THREAD

**Issue by Aziza8686** [maximegmd/CyberEngineTweaks#983]
# README

Github is NOT here for support and general questions, it's designed for developers to discuss development and code. If your issue is unrelated to anything technical, do not make an issue, you will be blocked and your issue closed without an answer.

# Bug

Operating system: W11 x64
Game version: 2.2
CET version: 1.34
GPU: 1070 Ti

## Description

 When I open the CET overlay the mouse isn't centered where the pointer is. It's legitimately about 2-3 inches off on my screen (27 inch display for reference). Didn't have this issue until I had to manually install due to CET not being updated on Nexus anymore.

## Expected behaviour

When moving the mouse or trying to use the overlay in general the actual pointer should be where the overlay registers

## Reproduction

I'm not sure why this is happening. 1.33 worked fine, as did previous versions installed with Vortex.

**Comment by WSSDude** [comment]
1.34.1 has a fix for mouse issues, you mention 1.34 which I assume is 1.34.0.

Try updating CET.

**Comment by Aziza8686** [comment]
I'm sorry, I forgot which was the latest. I just installed it yesterday morning. I didn't notice there was an updated one as of last night. Will try the updated one and report back whether fixed or not.

**Comment by WSSDude** [comment]
Welp, Ill just close this for now (wanted to before you replied), if the problem persists feel free to reopen as I formerly mentioned befofe editing my comment in reaction to your reply 😁
