### ISSUE TITLE
The game does not see the changes made to the flat values

### ISSUE THREAD

**Issue by AlexRynas** [maximegmd/CyberEngineTweaks#984]
![image](https://github.com/user-attachments/assets/245675fa-a5c8-42e2-85b2-9b0d5216c11b)
# Bug

Operating system: Windows 10
Game version: 2.2
CET version: 1.34.1
GPU: 4070 Ti

## Description

After making changes to flat values using TweakDB Editor and then loading the last save, the game does not react to the changes made, the commands TweakXL.Reload() and TweakXL.ExecuteAll() do not help. Can you check on your side if this issue is reproduced and that it is related to CET and not to the latest patch?

## Expected behaviour

After making changes to the flat values using TweakDB Editor, the game responds to the changes made.

## Reproduction

1) Load save file, open Photo Mode, switch to Preset 9, the FOV value should be 85, clode Photo Mode
2) Open TweakDB Editor. Open Flats tab and put into the search value "std_preset_9".
3) Change the flat photo_mode.std_preset_9.fov value to 55 for example.
4) Reload save file
5) Repeat the first step. If everything is working correctly, the FOV value should change from 85 to 55.

**Comment by WSSDude** [comment]
Many TweakDB edits need to be made during specific time. Game loads them once and never again.

This is known and not much we can do about it unfortunately.

There is `onTweak` event you can register inside your mod that is called before game even gets to the menu, that can be used to set up Tweaks programatically reliably.

I would encourage you to join our Discord server which you can find in the readme when you need modding help like this.

**Comment by WSSDude** [comment]
The TweakDB Editor is more like TweakDB Browser honestly. It can help you identify interesting bits, but as mentioned, many are just uneditable during the runtime unfortunately. Some can be edited but majority can't.

**Comment by WSSDude** [comment]
Also would quickly mention there is also TweakXL having much more options than CET offers when it comes to TweakDB editing many mods utilize. It also provides some extra functions you can callback into from CET.

WolvenKit can also be used for TweakDB manipulation but that one is purely offline. It can produce files usable with TweakXL.
