### ISSUE TITLE
Doesn't open menu

### ISSUE THREAD

**Issue by MeiCrypto** [maximegmd/CyberEngineTweaks#987]
# Bug

Operating system:  OS Name	Microsoft Windows 10 Home
Game version: 2.2
CET version: 1.34.1
GPU: 

## Description

On 14/12, I played with CET, and everything was working fine. Then I updated NVIDIA and Intel drivers.
Here is a screenshot of what I updated: ![CET](https://github.com/user-attachments/assets/14c26c99-e4c2-45e5-ab9e-839cf07b7c51) After updating, I uninstalled these programs, but the issue persisted.

## Expected behaviour
1
Write here what you expect to happen instead.

## Reproduction

Write here step by step how to reproduce the issue if applicable.

**Comment by MeiCrypto** [comment]
My GPU: NVIDIA GeForce RTX 3060 Laptop GPU

**Comment by WSSDude** [comment]
Go on Discord linked in readme to get help with this. This is not an issue for Git.
